# Generated by Django 5.2.13 on 2026-04-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Present"),
                            ("A", "Absent"),
                            ("L", "Late"),
                            ("H", "Holiday"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marked_by",
                    models.CharField(max_length=100, null=True, blank=True),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=100, null=True, blank=True),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("student", "date", "subject")},
            },
        ),
    ]
