# Generated by Django 5.2.13 on 2026-04-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="marked_by",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="subject",
        ),
    ]
