# Generated by Django 5.2.13 on 2026-04-25 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("fees", "Fees"),
                            ("marks", "Marks"),
                            ("attendance", "Attendance"),
                            ("timetable", "Timetable"),
                            ("event", "Event"),
                            ("holiday", "Holiday"),
                        ],
                        default="general",
                        max_length=15,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("standard", "Specific Standard"),
                            ("student", "Specific Student"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_standard",
                    models.CharField(max_length=100, null=True, blank=True),
                ),
                (
                    "target_students",
                    models.ManyToManyField(
                        blank=True, related_name="notifications", to="students.student"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("board", "Board Exam"),
                            ("unit_test", "Unit Test"),
                            ("midterm", "Mid-Term"),
                            ("model", "Model Paper"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                ("file", models.FileField(upload_to="question_papers/")),
                (
                    "solution_file",
                    models.FileField(
                        blank=True, null=True, upload_to="question_papers/solutions/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "standard",
                    models.CharField(max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_by",
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("notification", "user")},
            },
        ),
    ]
