# Generated by Django 5.2.13 on 2026-05-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuestionPaper",
        ),
    ]
