# Generated by Django 5.2.13 on 2026-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_fix_notification_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationread",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
