# Generated by Django 5.2.13 on 2026-04-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("notes", "Notes"),
                            ("assignment", "Assignment"),
                            ("worksheet", "Worksheet"),
                            ("reference", "Reference"),
                        ],
                        default="notes",
                        max_length=15,
                    ),
                ),
                ("file", models.FileField(upload_to="study_materials/")),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "chapter",
                    models.CharField(max_length=100, null=True, blank=True),
                ),
                (
                    "subject",
                    models.CharField(max_length=100),
                ),
                (
                    "uploaded_by",
                    models.CharField(max_length=100, null=True, blank=True),
                ),
            ],
        ),
    ]
