# Generated by Django 5.2.13 on 2026-05-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_delete_note"),
        ("study_material", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("standard", models.CharField(max_length=100)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("board", "Board Exam"),
                            ("unit_test", "Unit Test"),
                            ("midterm", "Mid-Term"),
                            ("model", "Model Paper"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                ("file", models.FileField(upload_to="question_papers/")),
                (
                    "solution_file",
                    models.FileField(
                        blank=True, null=True, upload_to="question_papers/solutions/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("download_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="chapter",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="subject",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="uploaded_by",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_important", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_material_notes",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
