# Generated by Django 5.2.13 on 2026-05-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study_material", "0002_questionpaper_alter_studymaterial_chapter_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudyMaterial",
        ),
    ]
