# Generated by Django 5.2.13 on 2026-06-06 13:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_delete_institute"),
        ("study_material", "0003_delete_studymaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="chapter",
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name="note",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="notes/pdfs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="standard",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name="note",
            name="subject",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="note",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: target a specific student. Leave empty for standard-wise notes.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_material_notes",
                to="students.student",
            ),
        ),
    ]
