# Generated by Django 5.2.13 on 2026-06-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_delete_institute"),
        ("study_material", "0004_note_chapter_note_pdf_file_note_standard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="standard",
            field=models.CharField(
                choices=[
                    ("5", "5th Standard"),
                    ("6", "6th Standard"),
                    ("7", "7th Standard"),
                    ("8", "8th Standard"),
                    ("9", "9th Standard"),
                    ("10", "10th Standard"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="Deprecated: notes are served standard-wise in the student app.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_material_notes",
                to="students.student",
            ),
        ),
    ]
