# Generated by Django 5.2.13 on 2026-06-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_material", "0006_normalize_note_standard_values"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Chapter-wise Note",
                "verbose_name_plural": "Chapter-wise Notes",
            },
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
