# Generated by Django 5.2.13 on 2026-06-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_material", "0007_alter_note_options_alter_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionpaper",
            name="standard",
            field=models.CharField(
                choices=[
                    ("5", "5th Standard"),
                    ("6", "6th Standard"),
                    ("7", "7th Standard"),
                    ("8", "8th Standard"),
                    ("9", "9th Standard"),
                    ("10", "10th Standard"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
