# Generated by Django 5.2.13 on 2026-04-26 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="gallery.gallerycategory",
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="gallery/"),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="media_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="video_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
