# Generated by Django 5.2.13 on 2026-04-26 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_galleryitem_category_alter_galleryitem_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galleryitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="event_date",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="file",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="media_type",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="title",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="video_url",
        ),
        migrations.CreateModel(
            name="GalleryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="gallery/")),
                ("video_url", models.CharField(blank=True, max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="gallery.galleryitem",
                    ),
                ),
            ],
        ),
    ]
