# Generated by Django 5.2.13 on 2026-04-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_remove_galleryitem_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryitem",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="gallery/"),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="video_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name="GalleryFile",
        ),
    ]
