# Generated by Django 5.2.13 on 2026-04-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecordedLecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("vimeo", "Vimeo"),
                            ("drive", "Google Drive"),
                            ("upload", "Direct Upload"),
                        ],
                        default="youtube",
                        max_length=10,
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="lectures/videos/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="lectures/thumbnails/"
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("view_count", models.IntegerField(default=0)),
                (
                    "chapter",
                    models.CharField(max_length=100, null=True, blank=True),
                ),
                (
                    "subject",
                    models.CharField(max_length=100),
                ),
                (
                    "teacher",
                    models.CharField(max_length=100, null=True, blank=True),
                ),
            ],
        ),
    ]
