# Generated by Django 5.2.13 on 2026-04-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="parent",
        ),
        migrations.AddField(
            model_name="student",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
