# Generated by Django 5.2.13 on 2026-04-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_remove_student_parent_student_mobile_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="institute",
        ),
        migrations.AddField(
            model_name="student",
            name="school_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
