# Generated by Django 5.2.13 on 2026-04-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_remove_student_institute_student_school_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
    ]
