# Generated by Django 5.2.13 on 2026-04-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="receive_admin_alerts",
            field=models.BooleanField(
                default=True,
                help_text="Whether this student should receive admin alerts and daily notifications",
            ),
        ),
    ]
