# Generated by Django 5.2.13 on 2026-04-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_student_receive_admin_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="standard",
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
    ]
