# Generated by Django 5.2.13 on 2026-04-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_student_standard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="standard",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1st Standard"),
                    ("2", "2nd Standard"),
                    ("3", "3rd Standard"),
                    ("4", "4th Standard"),
                    ("5", "5th Standard"),
                    ("6", "6th Standard"),
                    ("7", "7th Standard"),
                    ("8", "8th Standard"),
                    ("9", "9th Standard"),
                    ("10", "10th Standard"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
