# Generated by Django 5.2.13 on 2026-05-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_delete_note"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Institute",
        ),
    ]
