# Generated by Django 5.2.13 on 2026-06-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_delete_institute"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardFeatureAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("1", "1st Standard"),
                            ("2", "2nd Standard"),
                            ("3", "3rd Standard"),
                            ("4", "4th Standard"),
                            ("5", "5th Standard"),
                            ("6", "6th Standard"),
                            ("7", "7th Standard"),
                            ("8", "8th Standard"),
                            ("9", "9th Standard"),
                            ("10", "10th Standard"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "notes_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable Chapter-wise Notes for this standard.",
                    ),
                ),
                (
                    "question_papers_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable Question Papers for this standard.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Feature Access",
                "verbose_name_plural": "Standard Feature Access",
                "ordering": ["standard"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="notes_access_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Disable to hide and block Chapter-wise Notes for this student.",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="question_papers_access_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Disable to hide and block Question Papers for this student.",
            ),
        ),
    ]
