# Generated by Django 5.2.13 on 2026-04-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fee",
            old_name="amount_due",
            new_name="total_fee",
        ),
        migrations.RemoveField(
            model_name="fee",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="fee",
            name="fee_structure",
        ),
        migrations.AddField(
            model_name="fee",
            name="next_installment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fee",
            name="number_of_installments",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
